# coding: utf-8

"""
    Elastic Email REST API

    This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>

    The version of the OpenAPI document: 4.0.0
    Contact: support@elasticemail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ElasticEmail.api.domains_api import DomainsApi


class TestDomainsApi(unittest.TestCase):
    """DomainsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DomainsApi()

    def tearDown(self) -> None:
        pass

    def test_domains_by_domain_delete(self) -> None:
        """Test case for domains_by_domain_delete

        Delete Domain
        """
        pass

    def test_domains_by_domain_get(self) -> None:
        """Test case for domains_by_domain_get

        Load Domain
        """
        pass

    def test_domains_by_domain_put(self) -> None:
        """Test case for domains_by_domain_put

        Update Domain
        """
        pass

    def test_domains_by_domain_restricted_get(self) -> None:
        """Test case for domains_by_domain_restricted_get

        Check for domain restriction
        """
        pass

    def test_domains_by_domain_verification_put(self) -> None:
        """Test case for domains_by_domain_verification_put

        Verify Domain
        """
        pass

    def test_domains_by_email_default_patch(self) -> None:
        """Test case for domains_by_email_default_patch

        Set Default
        """
        pass

    def test_domains_get(self) -> None:
        """Test case for domains_get

        Load Domains
        """
        pass

    def test_domains_post(self) -> None:
        """Test case for domains_post

        Add Domain
        """
        pass


if __name__ == '__main__':
    unittest.main()
