# coding: utf-8

"""
    Elastic Email REST API

    This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>

    The version of the OpenAPI document: 4.0.0
    Contact: support@elasticemail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ElasticEmail.api.suppressions_api import SuppressionsApi


class TestSuppressionsApi(unittest.TestCase):
    """SuppressionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SuppressionsApi()

    def tearDown(self) -> None:
        pass

    def test_suppressions_bounces_get(self) -> None:
        """Test case for suppressions_bounces_get

        Get Bounce List
        """
        pass

    def test_suppressions_bounces_import_post(self) -> None:
        """Test case for suppressions_bounces_import_post

        Add Bounces Async
        """
        pass

    def test_suppressions_bounces_post(self) -> None:
        """Test case for suppressions_bounces_post

        Add Bounces
        """
        pass

    def test_suppressions_by_email_delete(self) -> None:
        """Test case for suppressions_by_email_delete

        Delete Suppression
        """
        pass

    def test_suppressions_by_email_get(self) -> None:
        """Test case for suppressions_by_email_get

        Get Suppression
        """
        pass

    def test_suppressions_complaints_get(self) -> None:
        """Test case for suppressions_complaints_get

        Get Complaints List
        """
        pass

    def test_suppressions_complaints_import_post(self) -> None:
        """Test case for suppressions_complaints_import_post

        Add Complaints Async
        """
        pass

    def test_suppressions_complaints_post(self) -> None:
        """Test case for suppressions_complaints_post

        Add Complaints
        """
        pass

    def test_suppressions_get(self) -> None:
        """Test case for suppressions_get

        Get Suppressions
        """
        pass

    def test_suppressions_unsubscribes_get(self) -> None:
        """Test case for suppressions_unsubscribes_get

        Get Unsubscribes List
        """
        pass

    def test_suppressions_unsubscribes_import_post(self) -> None:
        """Test case for suppressions_unsubscribes_import_post

        Add Unsubscribes Async
        """
        pass

    def test_suppressions_unsubscribes_post(self) -> None:
        """Test case for suppressions_unsubscribes_post

        Add Unsubscribes
        """
        pass


if __name__ == '__main__':
    unittest.main()
