# coding: utf-8

"""
    Elastic Email REST API

    This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: support@elasticemail.com
    Generated by: https://openapi-generator.tech
"""

from ElasticEmail.paths.suppressions_bounces.get import SuppressionsBouncesGet
from ElasticEmail.paths.suppressions_bounces_import.post import SuppressionsBouncesImportPost
from ElasticEmail.paths.suppressions_bounces.post import SuppressionsBouncesPost
from ElasticEmail.paths.suppressions_email.delete import SuppressionsByEmailDelete
from ElasticEmail.paths.suppressions_email.get import SuppressionsByEmailGet
from ElasticEmail.paths.suppressions_complaints.get import SuppressionsComplaintsGet
from ElasticEmail.paths.suppressions_complaints_import.post import SuppressionsComplaintsImportPost
from ElasticEmail.paths.suppressions_complaints.post import SuppressionsComplaintsPost
from ElasticEmail.paths.suppressions.get import SuppressionsGet
from ElasticEmail.paths.suppressions_unsubscribes.get import SuppressionsUnsubscribesGet
from ElasticEmail.paths.suppressions_unsubscribes_import.post import SuppressionsUnsubscribesImportPost
from ElasticEmail.paths.suppressions_unsubscribes.post import SuppressionsUnsubscribesPost


class SuppressionsApi(
    SuppressionsBouncesGet,
    SuppressionsBouncesImportPost,
    SuppressionsBouncesPost,
    SuppressionsByEmailDelete,
    SuppressionsByEmailGet,
    SuppressionsComplaintsGet,
    SuppressionsComplaintsImportPost,
    SuppressionsComplaintsPost,
    SuppressionsGet,
    SuppressionsUnsubscribesGet,
    SuppressionsUnsubscribesImportPost,
    SuppressionsUnsubscribesPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
